#ifndef SEQUENCE_STATE_VERSION_H
#define SEQUENCE_STATE_VERSION_H

#define SEQUENCE_STATE_LIBRARY_VERSION "0.1.0"
#define SEQUENCE_STATE_TRACE_VERSION "C-1.0"
#define SEQUENCE_STATE_COMPOSE_VERSION "H-1.0"
#define SEQUENCE_STATE_RANGE_VERSION "H2-1.0"

#endif
